### ISSUE TITLE
Better handle the case of missing API URL

### ISSUE THREAD

**Issue by mudrd8mz** [antriver/moodle-atto_mediadrop#1]
If the Mediadrop URL is not defined, the code still attempts to access it - leading to errors like

```
Warning: file_get_contents(/api/media?type=video&amp;limit=6&amp;offset=0&amp;search=):
failed to open stream: No such file or directory in
.../lib/editor/atto/plugins/mediadrop/classes/local/mediadrop.php on line 72
```

It would be nice to better handle the case of missing or invalid URL.

**Comment by antriver** [comment]
Hi,

This has been addressed in be63ffa9433dba8cbdc2adc20ad996162354fdee

Thanks
